import { describe, expect, it } from 'vitest'
import { KEYS, META_PREFIX_MS, inkKeyName, matches, wordJumpAfterEscape } from '../src/keys.ts'

describe('inkKeyName', () => {
  it('maps Ink 5 shift+tab and page flags, not bare tab', () => {
    expect(inkKeyName('', { tab: true, shift: true })).toBe('shift+tab')
    expect(inkKeyName('', { tab: true })).toBe('tab')
    expect(inkKeyName('', { pageUp: true })).toBe('pageup')
    expect(inkKeyName('', { pageDown: true })).toBe('pagedown')
    expect(inkKeyName('', { pageup: true })).toBe('pageup')
    expect(inkKeyName('', { pagedown: true })).toBe('pagedown')
    expect(inkKeyName('', { upArrow: true, shift: true })).toBe('shift+up')
    expect(inkKeyName('', { downArrow: true, shift: true })).toBe('shift+down')
    expect(inkKeyName('', { upArrow: true })).toBe('up')
    expect(inkKeyName(String.fromCharCode(27) + '[Z', {})).toBe('shift+tab')
    expect(inkKeyName(String.fromCharCode(27) + '[5~', {})).toBe('pageup')
    expect(inkKeyName(String.fromCharCode(27) + '[6~', {})).toBe('pagedown')
  })

  it('maps Ink 5 Backspace reports to backspace, CSI [3~ to delete', () => {
    expect(inkKeyName('', { backspace: true })).toBe('backspace')
    expect(inkKeyName('', { delete: true })).toBe('backspace')
    expect(inkKeyName('\x7f', {})).toBe('backspace')
    expect(inkKeyName('\x7f', { delete: true })).toBe('backspace')
    expect(inkKeyName('\b', {})).toBe('backspace')
    expect(inkKeyName('\b', { backspace: true })).toBe('backspace')
    expect(inkKeyName(String.fromCharCode(27) + '[3~', {})).toBe('delete')
    expect(inkKeyName(String.fromCharCode(27) + '[3~', { delete: true })).toBe('delete')
    expect(inkKeyName(String.fromCharCode(27) + '[3;2~', {})).toBe('delete')
    expect(inkKeyName('h', { ctrl: true })).toBe('ctrl+h')
    expect(inkKeyName('d', { ctrl: true })).toBe('ctrl+d')
    expect(inkKeyName('k', { ctrl: true })).toBe('ctrl+k')
  })

  it('maps arrow flags before escape so CSI arrows are not cancel', () => {
    expect(inkKeyName('', { escape: true, upArrow: true })).toBe('up')
    expect(inkKeyName('', { escape: true, downArrow: true })).toBe('down')
    expect(inkKeyName('', { escape: true, leftArrow: true })).toBe('left')
    expect(inkKeyName('', { escape: true, rightArrow: true })).toBe('right')
    expect(inkKeyName('', { escape: true, upArrow: true, shift: true })).toBe('shift+up')
    expect(inkKeyName('', { escape: true })).toBe('escape')
    expect(matches(KEYS.pageUp, 'up')).toBe(false)
    expect(matches(KEYS.pageDown, 'down')).toBe(false)
  })

  it('maps Option/Alt/Ctrl+Left/Right to word-jump names, not bare left/right', () => {
    expect(inkKeyName('', { leftArrow: true, meta: true })).toBe('alt+left')
    expect(inkKeyName('', { rightArrow: true, meta: true })).toBe('alt+right')
    expect(inkKeyName('', { leftArrow: true, ctrl: true })).toBe('alt+left')
    expect(inkKeyName('', { rightArrow: true, ctrl: true })).toBe('alt+right')
    expect(inkKeyName('', { leftArrow: true, meta: true, escape: true })).toBe('alt+left')
    expect(inkKeyName('', { leftArrow: true })).toBe('left')
    expect(inkKeyName('', { rightArrow: true })).toBe('right')
    expect(inkKeyName('', { escape: true, downArrow: true })).toBe('down')
    expect(inkKeyName('b', { meta: true })).toBe('alt+b')
    expect(inkKeyName('f', { meta: true })).toBe('alt+f')
    expect(inkKeyName(String.fromCharCode(27) + 'b', {})).toBe('alt+b')
    expect(inkKeyName(String.fromCharCode(27) + 'f', {})).toBe('alt+f')
    expect(inkKeyName(String.fromCharCode(27) + '[1;3D', {})).toBe('alt+left')
    expect(inkKeyName(String.fromCharCode(27) + '[1;3C', {})).toBe('alt+right')
    expect(inkKeyName(String.fromCharCode(27) + '[1;5D', {})).toBe('alt+left')
    expect(inkKeyName(String.fromCharCode(27) + '[1;5C', {})).toBe('alt+right')
    expect(inkKeyName('[1;3D', {})).toBe('alt+left')
    expect(inkKeyName('[1;3C', {})).toBe('alt+right')
    expect(inkKeyName('[1;5D', {})).toBe('alt+left')
    expect(inkKeyName('[1;5C', {})).toBe('alt+right')
    expect(inkKeyName('[1;7D', {})).toBe('alt+left')
    expect(inkKeyName('[1;7C', {})).toBe('alt+right')
    expect(inkKeyName('[1;9D', {})).toBe('alt+left')
    expect(inkKeyName('[1;9C', {})).toBe('alt+right')
    expect(inkKeyName('[3D', {})).toBe('alt+left')
    expect(inkKeyName('[3C', {})).toBe('alt+right')
    expect(inkKeyName('[5D', {})).toBe('alt+left')
    expect(inkKeyName('[5C', {})).toBe('alt+right')
    expect(inkKeyName(String.fromCharCode(27) + '[1;7D', {})).toBe('alt+left')
    expect(inkKeyName(String.fromCharCode(27) + '[1;9C', {})).toBe('alt+right')
    expect(inkKeyName(String.fromCharCode(27) + '[3D', {})).toBe('alt+left')
    expect(inkKeyName(String.fromCharCode(27) + '[5C', {})).toBe('alt+right')
    expect(inkKeyName('b', { ctrl: true })).toBe('ctrl+b')
  })

  it('maps a following b/f after Esc to readline meta word-jump names', () => {
    expect(META_PREFIX_MS).toBe(400)
    expect(wordJumpAfterEscape('b')).toBe('alt+b')
    expect(wordJumpAfterEscape('B')).toBe('alt+b')
    expect(wordJumpAfterEscape('alt+b')).toBe('alt+b')
    expect(wordJumpAfterEscape('f')).toBe('alt+f')
    expect(wordJumpAfterEscape('F')).toBe('alt+f')
    expect(wordJumpAfterEscape('alt+f')).toBe('alt+f')
    expect(wordJumpAfterEscape('left')).toBeUndefined()
    expect(wordJumpAfterEscape('escape')).toBeUndefined()
    expect(wordJumpAfterEscape('x')).toBeUndefined()
  })

  it('matches page aliases including shift+up / shift+down', () => {
    expect(matches(KEYS.pageUp, 'pageup')).toBe(true)
    expect(matches(KEYS.pageUp, 'shift+up')).toBe(true)
    expect(matches(KEYS.pageUp, 'pageUp')).toBe(true)
    expect(matches(KEYS.pageDown, 'pagedown')).toBe(true)
    expect(matches(KEYS.pageDown, 'shift+down')).toBe(true)
    expect(matches(KEYS.permission, 'shift+tab')).toBe(true)
  })

  it('does not map Shift+T to steer; Ctrl+T is the advertised steer key', () => {
    expect(inkKeyName('T', { shift: true })).toBe('T')
    expect(inkKeyName('t', { shift: true })).toBe('t')
    expect(inkKeyName('t', { ctrl: true })).toBe('ctrl+t')
    expect(inkKeyName('T', { ctrl: true })).toBe('ctrl+T')
    expect(KEYS.steer.key).toBe('ctrl+t')
    expect(KEYS.steer.help).toBe('ctrl+t')
    expect(KEYS.steer.aliases).toEqual(['ctrl+enter', 'ctrl+T'])
    expect(matches(KEYS.steer, 'ctrl+t')).toBe(true)
    expect(matches(KEYS.steer, 'ctrl+enter')).toBe(true)
    expect(matches(KEYS.steer, 'ctrl+T')).toBe(true)
    expect(matches(KEYS.steer, 'shift+t')).toBe(false)
  })
})
